name: Destroy Terraform

on:
  workflow_dispatch:  # Permitir ejecución manual
  push:
    branches:
      - main  # Se ejecuta cuando hay cambios en `main`

jobs:
  terraform-destroy:
    if: ${{ vars.ENABLE_DESTROY == 'true' }}  # Solo corre si está en true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Initialize Terraform
        run: terraform init

      # Plan the destroy (ve lo que se va a eliminar)
      - name: Terraform Destroy Plan
        run: terraform plan -destroy -out=tfplan

      # Realizar el destroy
      - name: Terraform Destroy
        run: terraform apply -auto-approve tfplan
